# Collision Feature
report_validity: false
collision_clearance: 0.01
debug_collisions: false

# Stomp Optimization Task
num_feature_basis_functions: 1
trajectory_duration: 4.0
num_time_steps: 100

# Stomp Planner init()
collision_space:
  size_x: 8.0
  size_y: 8.0
  size_z: 8.0
  origin_x: 0.0
  origin_y: 0.0
  origin_z: 0.0
  resolution: 0.05
  collision_tolerance: 0.04
  max_propagation_distance: 0.25

# Stomp Planner solve()
max_rollouts: 100

# Unknown
min_rollouts: 20
num_rollouts_per_iteration: 16
use_noise_adaptation: true
#noise_stddev: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
#noise_stddev: [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
noise_min_stddev: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
#noise_stddev: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
noise_stddev: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
noise_decay: [0.999, 0.999, 0.999, 0.999, 0.999, 0.999, 0.999]
write_to_file: false
use_openmp: false

features: 
-
  class: stomp_moveit_interface/CollisionFeature
  report_validity: false # report state validity based on distance field
  collision_clearance: 0.02
  debug_collisions: false
